[tool.poetry]
name = "petroly-django"
version = "1.0.0"
description = "Petroly Initiative backend and API"
authors = ["ammar-faifi <a@ammarf.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "3.11.1"
Django = "^4.1.5"
django-q = "^1.3.9"
django-choices-field = "^2.1"
django-cors-headers = "^3.13.0"
gunicorn = "^20.1.0"
Pillow = "^9.4.0"
psycopg2 = "^2.9.5"
strawberry-django-auth = "0.3.4.1"
strawberry-django-jwt = "^0.2.3"
strawberry-django-plus = "^2.0.0"
strawberry-graphql = "0.152.0"
strawberry-graphql-django = "0.8.2"
whitenoise = "^6.3.0"
cloudinary = "^1.30.0"
python-telegram-bot = {extras = ["callback-data"], version = "^20.0"}
django-multiselectfield = "^0.1.12"
cryptography = "^39.0.0"
requests = "^2.28.1"
django-email-verification = "^0.3.1"
django-filter = "^22.1"
dj-database-url = "^1.2.0"
django-debug-toolbar = "^3.8.1"
beautifulsoup4 = "^4.11.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
mypy = "^0.991"
pylint-django = "^2.5.3"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
