[tool.poetry]
name = "petroly-django"
version = "1.0.0"
description = "Petroly Initiative backend and API"
authors = ["ammar-faifi <a@ammarf.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "3.11.1"
Django = "^4.1.9"
django-q = "^1.3.9"
django-choices-field = "^2.1"
django-cors-headers = "^4.0.0"
gunicorn = "^20.1.0"
Pillow = "^9.5.0"
psycopg2 = "^2.9.6"
strawberry-django-auth = "0.374.3"
strawberry-django-plus = "^1.33.1"
strawberry-graphql = "0.159.0"
strawberry-graphql-django = "0.9.3"
whitenoise = "^6.4.0"
cloudinary = "^1.33.0"
python-telegram-bot = {extras = ["callback-data"], version = "^20.3"}
django-multiselectfield = "^0.1.12"
cryptography = "^41.0.1"
requests = "^2.31.0"
django-email-verification = "^0.3.1"
django-filter = "^23.2"
dj-database-url = "^2.0.0"
django-debug-toolbar = "^4.1.0"
beautifulsoup4 = "^4.12.2"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.4"
pylint-django = "^2.5.3"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
